baseurl = "/"
title = "YUCPC-山梨大学競技プログラミング部"
theme = "hugo-universal-theme"
languageCode = "ja-jp"
hasCJKLanguage = true
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "ja"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "author"

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="about"
    name = "About"
    url  = "/about/"
    weight = 2

[[menu.main]]
    identifier="news"
    name = "News"
    url  = "/news/"
    weight = 3    

[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 4

[[menu.main]]
    identifier="joinus"
    name = "入部希望の方へ"
    url  = "/joinus/"
    weight = 5

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 6

# Top bar social links menu

#[[menu.topbar]]
#    weight = 1
#    name = "GitHub"
#    url = "https://github.com/devcows/hugo-universal-theme"
#    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 1
    name = "Email"
    url = "mailto:yucpclub@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com/yucpclub"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "yucpc"
    defaultKeywords = ["yucpc", "icpc",]
    mainSections = ["blog"]
    defaultDescription = "The homepage of YUCPC"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "yucpclub" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"

    email = "yucpclub@gmail.com"
    contact_form_ajax = false

    ##about_us = "<p>競技プログラミングをテーマに活動する公認サークルです</p>"
    copyright = "Copyright (c) 2018 - 2019, University of Yamanashi Competitive Programming Club; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class="hidden-sm hidden-xs">...</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      
      """
    latitude = "-12.043333"
    longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"


# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = ""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "案内"
    subtitle = ""

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "YUCPC山梨大学競技プログラミング部"
    subtitle = "山梨大学競技プログラミング部は，2018年10月23日に設立された公認サークルです．<p>私達は，競技プログラミング（通称競プロ）をテーマに活動しています．</p>"
    link_url = "/about"
    link_text = "もっと詳しく"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "関連リンク"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "New Blog"
    subtitle = ""
