media_folder = "site/static/img"
public_folder = "img"
publish_mode = "editorial_workflow"

[backend]
  name = "git-gateway"

[[collections]]
  create = true
  folder = "site/content/blog"
  label = "Blog"
  name = "blog"
  slug = "{{year}}-{{month}}-{{day}}-{{slug}}"

  [[collections.fields]]
    label = "Title"
    name = "title"
    widget = "string"

  [[collections.fields]]
    label = "Publish Date"
    name = "date"
    widget = "datetime"

  [[collections.fields]]
    label = "Category"
    name = "category"
    widget = "string"

  [[collections.fields]]
    label = "Tags"
    name = "tags"
    required = false
    widget = "string"

  [[collections.fields]]
    label = "Intro Blurb"
    name = "description"
    widget = "text"

  [[collections.fields]]
    label = "Image"
    name = "image"
    required = false
    widget = "image"

  [[collections.fields]]
    label = "Body"
    name = "body"
    widget = "markdown"

[[collections]]
  create = true
  folder = "site/content/news"
  label = "News"
  name = "news"
  slug = "{{year}}-{{month}}-{{day}}-{{slug}}"

  [[collections.fields]]
    label = "Title"
    name = "title"
    widget = "string"

  [[collections.fields]]
    label = "Publish Date"
    name = "date"
    widget = "datetime"

  [[collections.fields]]
    label = "Category"
    name = "category"
    required = false
    widget = "string"

  [[collections.fields]]
    label = "Tags"
    name = "tags"
    required = false
    widget = "string"

  [[collections.fields]]
    label = "Intro Blurb"
    name = "description"
    widget = "text"

  [[collections.fields]]
    label = "Image"
    name = "image"
    required = false
    widget = "image"

  [[collections.fields]]
    label = "Body"
    name = "body"
    widget = "markdown"
